### ISSUE TITLE
继续调整封装, button 可以简化一下

### ISSUE THREAD

**Issue by tiye** [teambition/react-lite-uploader#3]
然后也用回调函数的方式提供. 而 input 标签挂载到全局去. 保持原有的 DOM 结构清晰.

**Comment by zzz6519003** [comment]
use `hub` XD

**Comment by tiye** [comment]
@zzz6519003 太精简没看明白.

**Comment by zzz6519003** [comment]
there's a great command line tool named hub  XD

**Comment by tiye** [comment]
not related to the topic I think.. @zzz6519003

**Comment by tiye** [comment]
已经调整为 callback 了, 关闭任务
